# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "274cc7aa84961d999a946c409d62ad46"
name = "Gift Product"
handle = "gift-product-11783"
application_url = "https://thunder-blue-ethiopia-trackbacks.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://shed-classical-assured-sees.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://shed-classical-assured-sees.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_content,write_files,write_products,write_orders,write_publications"

[auth]
redirect_urls = [
  "https://thunder-blue-ethiopia-trackbacks.trycloudflare.com/auth/callback",
  "https://thunder-blue-ethiopia-trackbacks.trycloudflare.com/auth/shopify/callback",
  "https://thunder-blue-ethiopia-trackbacks.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
